import { Karla } from "next/font/google";
import "./globals.css";

const karla = Karla({
  variable: "--font-h1",
  subsets: ["latin"],
});

export const metadata = {
  title: "EnDance",
  icons: {
    icon: "/endance-favicon.svg",
  },
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${karla.variable} antialiased`} style={{ background: '#e0e0e0' }}>
        {children}
      </body>
    </html>
  );
}

